/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const toolbar: string;
declare const icon: string;

export {
	toolbar,
	icon
};
