/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const toolbar: string;
declare const icon: string;
declare const select: string;
declare const editorPane: string;
declare const legend: string;
declare const legendList: string;

export {
	toolbar,
	icon,
	select,
	editorPane,
	legend,
	legendList
};
