/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const editor: string;
declare const gutter: string;
declare const editable: string;

export {
	editor,
	gutter,
	editable
};
