/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const redSection: string;
declare const greenSection: string;
declare const blueSection: string;
declare const yellowSection: string;
declare const graySection: string;

export {
	redSection,
	greenSection,
	blueSection,
	yellowSection,
	graySection
};
