/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const red: string;
declare const redAlt: string;
declare const redLight: string;
declare const redDark: string;
declare const redGradient: string;
declare const green: string;
declare const greenAlt: string;
declare const greenLight: string;
declare const greenDark: string;
declare const greenGradient: string;
declare const blue: string;
declare const blueAlt: string;
declare const blueLight: string;
declare const blueDark: string;
declare const blueGradient: string;
declare const yellow: string;
declare const yellowAlt: string;
declare const yellowLight: string;
declare const yellowDark: string;
declare const yellowGradient: string;
declare const gray: string;
declare const grayAlt: string;
declare const grayLight: string;
declare const grayDark: string;
declare const grayGradient: string;

export {
	red,
	redAlt,
	redLight,
	redDark,
	redGradient,
	green,
	greenAlt,
	greenLight,
	greenDark,
	greenGradient,
	blue,
	blueAlt,
	blueLight,
	blueDark,
	blueGradient,
	yellow,
	yellowAlt,
	yellowLight,
	yellowDark,
	yellowGradient,
	gray,
	grayAlt,
	grayLight,
	grayDark,
	grayGradient
};
